### ISSUE TITLE
Broken link - cannot download Processing library

### ISSUE THREAD

**Issue by MMIX2009** [Qatja/processing#4]
Hi,
I tried downloading the Processing library from this link: http://www.santiclaws.se/qatja/Qatja.zip
The link appears to be broken.
Where can I download the library?
Thanks,

**Comment by agoransson** [comment]
Hey, sorry for late response. Yes, that link is broken since a long time - the processing lib has not seen any updates for about 5 years now and I haven't had an opportunity to verify that it still works with the current version of processing.

I will try to get a moment today to verify that it still works - and if it does I'll create a new downloadable link.

**Comment by agoransson** [comment]
I've uploaded it as a pre-release here at Github instead.

https://github.com/Qatja/processing/releases/tag/0.1.1
